chore(travis): fix travis build error
error: cp: cannot stat '.env.test.example': No such file or directory

fix:

change .travis.yml to .env.test instead of a copy of .env.test.example.

see issues: #27 #31

see build details: https://travis-ci.com/joshuamabina/express-starter/builds/123593903